# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=-1),
        ),
    ]
