# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home',
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
