# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-22 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20170122_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='preview',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
