# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_auto_20170119_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='owner',
        ),
    ]
