# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0009_auto_20170121_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='book',
        ),
        migrations.AddField(
            model_name='category',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lib.Book'),
            preserve_default=False,
        ),
    ]
