# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-21 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0010_auto_20170121_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lib.Book'),
        ),
    ]
